name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - name: Run npm install
      run: npm ci
    - name: Run headless test
      uses: coactions/setup-xvfb@v1
      with:
        run: npm test
